name: jaded
version: 1.0.0
author: Demis Bellot <demis.bellot@gmail.com>
description: Port of node.js popular Jade view engine for Dart.
homepage: https://github.com/dartist/jaded
documentation: https://github.com/visionmedia/jade/blob/master/Readme.md
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  character_parser:
    git: https://github.com/mobilemindtec/character_parser.git
  markdown: "^2.0.3"
  node_shims:
    git: https://github.com/mobilemindtec/node_shims.git
dev_dependencies:
  test: ^1.0.0
